"""empty message

Revision ID: 93a42c57235f
Revises: 305009ae1041
Create Date: 2025-04-04 11:55:07.027988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93a42c57235f'
down_revision = '305009ae1041'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopping_list_item', schema=None) as batch_op:
        batch_op.alter_column('is_marked',
               existing_type=sa.BOOLEAN(),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopping_list_item', schema=None) as batch_op:
        batch_op.alter_column('is_marked',
               existing_type=sa.Integer(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)

    # ### end Alembic commands ###
